#!/usr/bin/perl

my $package = "unknown";

my $ver = 4;
my $maj = 8;
my $min = 0;

my $out = "";

open (CONTROL, "<debian/control");
while (my $l = <CONTROL>) {
    chomp($l);
    if ($l =~ /Source: (.*)/) {
        $package = $1;
    }
}
close(CONTROL);

open(LOG, "git log --reverse --pretty=format:'%aN|%aE|%cD|%s'|");
while (my $l = <LOG>) {
    chomp($l);
    my ($author, $email, $time, $subject) = split(/\|/, $l);
    my $add = "$package ($ver.$maj.$min) uecide; urgency=low\n";
    $add .= "\n";
    $add .= "  * $subject\n";
    $add .= "\n";
    $add .= " -- $author <$email>  $time\n";
    $add .= "\n";
    $min++;
    if ($min == 100) {
        $min = 0;
        $maj++;
    }
    $out = $add . $out;
}
close(LOG);


my $oldMD5 = `md5sum debian/changelog`;
open(CL, ">debian/changelog");
print CL $out;
close(CL);
